### ISSUE TITLE
AusgabeDesPrueflings Programmierung

### ISSUE THREAD

**Issue by holzfelix** [TeamProjektWS1415/rere#37]

**Comment by holzfelix** [comment]
wie ist der stand?

**Comment by ti-wa** [comment]
Problem beim Aufruf des Controllers über das Select-Object, bin dran.

**Comment by ti-wa** [comment]
Der aktuelle Prüfling ist hart codiert als id drinnen. Da aber ein Issue für den Login offen ist mache ich hier zu, der Rest ist fertig.
