### ISSUE TITLE
Selenium

### ISSUE THREAD

**Issue by holzfelix** [TeamProjektWS1415/rere#46]

**Comment by holzfelix** [comment]
kannst du dir das in phpunit integrierte noch anschauen und vielleicht erste gehversuche damit machen? ... die zeit drängt ;)

**Comment by tobrockn** [comment]
Test von Modul anlegen(alle möglichkeiten), Fach hinzufügen(alle Möglichkeiten), Prüfling anlegen(alle Möglichkeiten), Prüfling zuweisen und Note zuweisen aufgenommen und funktionsfähig.
Import, Export, User-Group, Frontend noch nicht getestet, da noch nicht möglich

**Comment by tobrockn** [comment]
Anleitung hinzugefügt
