### ISSUE TITLE
ReadMe-Schreiben

### ISSUE THREAD

**Issue by holzfelix** [TeamProjektWS1415/rere#49]

**Comment by holzfelix** [comment]
Readme bitte Rechtschreibung und Grammatik prüfen.

Übersetzung der GPL v2 sofern wirklich eforderlich durch eine Rechtsgültige oder zumindest Inhaltserhaltende Version ersetzen...

http://www.gnu.de/documents/gpl-2.0.de.html

**Comment by semangko** [comment]
GPL v2 hinzugefügt.
Rechtschreibsprüfung und Grammatikprüfung kommen noch

**Comment by semangko** [comment]
ReadMe korrigiert (von Tobi) und aktualisiert. Jetzt ist i.O
