### ISSUE TITLE
Software-Architektur-Dokument prüfen ob es mit dem entwickelten übereinstimmt

### ISSUE THREAD

**Issue by holzfelix** [TeamProjektWS1415/rere#51]

**Comment by holzfelix** [comment]
Tabellen Struktur muss auf jeden Fall angepasst werden! 
KlassenDiagramm ebenso!

**Comment by holzfelix** [comment]
erledigt:
Datenbank Schema angepasst

Offen:
Datenbankalgebra anpassen
Klassendiagramm anpassen


Sarah bitte Datenbankalgebra anpassen

**Comment by Elfentraum** [comment]
Datenbankalgebra angepasst

**Comment by holzfelix** [comment]
offen: Klassendiagramm anpassen

Wer sieht sich in der Lage dies anzupassen?

**Comment by holzfelix** [comment]
offen: Klassendiagramm anpassen

Wer sieht sich in der Lage dies anzupassen?

**Comment by holzfelix** [comment]
Verdammt Leute .. irgendjemand der nicht programmiert muss sich dazu bereit erklären das Klassen diagramm anzupassen!

**Comment by NeBalta** [comment]
ich schau es mir an =)

**Comment by NeBalta** [comment]
Klassendiagramm erstellt und in der Dropbox unter UMLDiagramme hochgeladen

**Comment by holzfelix** [comment]
Bitte wie besprochen anpassen

**Comment by NeBalta** [comment]
Angepasst

**Comment by holzfelix** [comment]
hab dir nochmals änderungen geschickt diese bitte noch einpflegen

**Comment by NeBalta** [comment]
erledigt
