### ISSUE TITLE
AntScript schreiben

### ISSUE THREAD

**Issue by holzfelix** [TeamProjektWS1415/rere#60]
kleines antscript schreiben, welches sonarqube startet und phpdoc startet

**Comment by holzfelix** [comment]
Nejat du kannst mal anfagen mit dem Antscript

- Es soll folgendes können:

- phpdoc generierung: aufruf von  apigen
- sonarqube starten aufruf von start "" "C:\sonar-runner-2.4\bin\sonar-runner.bat" im verzeichnis der extension
- Deployment des moduls auf den Test-Server

**Comment by holzfelix** [comment]
wie ist hier der stand?

**Comment by NeBalta** [comment]
Hab mich erkundigt und fang bald an den Code zu schreiben

**Comment by holzfelix** [comment]
wie ist der stand?

**Comment by NeBalta** [comment]
Soweit wie ich dir das letztens bei Facebook mitgeteilt habe.

Habe es nochmal versucht, aber nichts richtiges hinbebkommen und die letzten Tage musste ich ne Ausarbeitung schreiben :/

Bis wann brauchst du das den ?

**Comment by holzfelix** [comment]
schön wäre wenn ich mitte nächster Woche etwas hätte

**Comment by holzfelix** [comment]
brauchen wir auf alle fälle gibt einen Punkt nach unserer Vorlage!

**Comment by holzfelix** [comment]
Sonar Qube über ant läuft

Phpdoc fehlt noch

**Comment by holzfelix** [comment]
Php Doc generierung klappt nun auch.


es soll versucht werden dieses script einzuninden:
https://gist.github.com/davejlong/874521

**Comment by holzfelix** [comment]
bis auf pushen läuft auch git unter windows. für mac muss man lediglich den pfad anpassen dann sollte das auch unterm mac gehen

pushen lass ich absichtlich nicht dass man ausversehen was pushed
