### ISSUE TITLE
Systemtest

### ISSUE THREAD

**Issue by ti-wa** [TeamProjektWS1415/rere#66]
Sämtliche Funktionalitäten auf dem Testserver durchprobieren. 
Überprüfen ob Eingaben und Ausgaben zusammen passen bei größeren Mengen an Datensätzen und Usern.

**Comment by holzfelix** [comment]
Was mir im Frontend aufgefallen ist, wenn ein Prüfling noch keiner Prüfung zugewiesen wurde dann erscheint nur eine weiße seite ... das sollte durch einen entsprechenden Hinweiß noch gefixt werden ... erledige ich aber habs nur mal aufgeschrieben dass ichs nicht vergesse

**Comment by holzfelix** [comment]
entsprechende Meldung wird angezeigt

**Comment by holzfelix** [comment]
alles erledigt
