### ISSUE TITLE
Mailbug

### ISSUE THREAD

**Issue by ti-wa** [TeamProjektWS1415/rere#67]
Die Mailfunktion an neue FE-User funktioniert noch nicht optimal.

**Comment by holzfelix** [comment]
Tim bekommt keine Emails, bei Sarah und bei mir klappt es. Hier muss geprüft werden wieso Tim keine Mails bekommt. Eventuell Spam-Filter geschichten ??

**Comment by holzfelix** [comment]
Mails werden nun korrekt versendet lag an der "Fake Email" adresse
