### ISSUE TITLE
Backenend: Modulnummer ausblenden lassen wenn nicht vorhanden

### ISSUE THREAD

**Issue by ti-wa** [TeamProjektWS1415/rere#69]
Die Modulnummer soll in den Übersicht ausgeblendet werden wenn ihr kein Wert zugewiesen wurde.(Wert = 0)

**Comment by holzfelix** [comment]
bei mir ist es gefixt, tim kannst du es bitte bei dir prüfen und schauen ob es auch für die bestandsdaten klappt

**Comment by ti-wa** [comment]
Klappt
